### ISSUE TITLE
tanzu package install errors out even though package install seems successful

### ISSUE THREAD

**Issue by saji-pivotal** [vmware-tanzu/tanzu-framework#2188] opened 2022-04-19 23:39 UTC
**Bug description**

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [X] Addons
- [X] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
`tanzu package install` does not return an error after a successful package install

**Steps to reproduce the bug**
1. Create and publish a deployment as a package
2. kubeapply the package, and packagemetadata to a management cluster
3. Run `tanzu package install <package-name>`
4. The package install errors out with 
```
Error: resource reconciliation failed: kapp: Error: Trying to apply empty set of resources will result in deletion of resources on cluster. Refusing to continue unless --dangerous-allow-empty-list-of-resources is specified.. Reconcile failed: Error (see .status.usefulErrorMessage for details)
Error: exit status 1

✖  exit status 1
```
5. Running `kubectl get` on the Package, PackageMetadata, PackageInstall, Deployment resources seem to indicate no errors in any of them

**Version** (include the SHA if the version is not obvious)
v0.21.0-dev

**Environment where the bug was observed (cloud, OS, etc)**
azure

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by shivaani0505** [comment] 2022-04-26 17:21
After reproducing the above issue, Step 3 mentioned here is incomplete.
We need to specify the command as:
`tanzu package install my-autoscaler -p tkg-autoscaler.tanzu.vmware.com --version 0.21.0-dev -f /tmp/values.yaml`

We need this values file populated, before executing above:
```
CLUSTER_NAME: test-wc
NAMESPACE: default
ENABLE_AUTOSCALER: true
AUTOSCALER_MAX_NODES_TOTAL: "0"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_ADD: "10m"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_DELETE: "10s"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_FAILURE: "3m"
AUTOSCALER_SCALE_DOWN_UNNEEDED_TIME: "10m"
AUTOSCALER_MAX_NODE_PROVISION_TIME: "15m"
AUTOSCALER_MIN_SIZE_0:
AUTOSCALER_MAX_SIZE_0:
AUTOSCALER_MIN_SIZE_1:
AUTOSCALER_MAX_SIZE_1:
AUTOSCALER_MIN_SIZE_2:
AUTOSCALER_MAX_SIZE_2:
TKG_CLUSTER_ROLE: workload
PROVIDER_TYPE: azure
```
2. We need a workload cluster available to install the autoscaler package

After following the above steps, the package install for the autoscaler package succeeds.
Since it is not a bug, I am closing the issue.

**Closed by shivaani0505** 2022-04-26 17:21 UTC
Labels: area/addons, kind/bug
