### ISSUE TITLE
Improve messaging when no AD/LDAP integration configured

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/tanzu-framework#568] opened 2021-09-06 14:57 UTC
## Feedback

Assuming that TCE/TKG has been deployed without any AD/LDAP integration (pinniped),  an attempt to get cluster credentials without the --admin option fails as follows:

```
$ tanzu cluster kubeconfig get tkg-workload-1
Error: failed to get pinniped-info from management cluster: failed to get pinniped-info from the cluster
Usage:
  tanzu cluster kubeconfig get CLUSTER_NAME [flags]

Examples:

    # Get workload cluster kubeconfig
    tanzu cluster kubeconfig get CLUSTER_NAME

    # Get workload cluster admin kubeconfig
    tanzu cluster kubeconfig get CLUSTER_NAME --admin

Flags:
      --admin                Get admin kubeconfig of the workload cluster
      --export-file string   File path to export a standalone kubeconfig for workload cluster
  -h, --help                 help for get
  -n, --namespace string     The namespace where the workload cluster was created. Assumes 'default' if not specified.

Global Flags:
      --log-file string   Log file path
  -v, --verbose int32     Number for the log level verbosity(0-9)

Error: exit status 1

✖  exit status 1
```

I'm wondering if all TCE/TKG customers will understand what _pinniped_ is in this case? Should we make this error easier to understand without using references to features/products?

## Suggested Changes

Instead of failing with:

`Error: failed to get pinniped-info from management cluster: failed to get pinniped-info from the cluster`

Perhaps we could make it more generic:

`Error: Identity service does not appear to be configured in management cluster: cannot get credentials of cluster as current user. Consider fetching credentials as admin`

## Environment Details

* Build version (`tanzu version`):  TKG 1.4 RTM
  version: v1.4.0
  buildDate: 2021-09-05
  sha: 905b9a66
* Operating System (client): Ubuntu 17.10

**Comment by saji-pivotal** [comment] 2021-10-14 22:57
This is a duplicate of https://github.com/vmware-tanzu/tanzu-framework/issues/833

**Closed by saji-pivotal** 2021-10-14 22:57 UTC
Labels: area/ux
