### ISSUE TITLE
tanzu "package installed delete" output looks like a failure for a partially installed package

### ISSUE THREAD

**Issue by zrob** [vmware-tanzu/tanzu-framework#728] opened 2021-09-30 22:55 UTC
**Bug description**

When installing a package fails due to a values file issue, some resources are created, such as secrets, but not all of the package information is created. This causes a follow up delete to fail.

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

It is possible to delete the resources that are created by a partially installed package.

**Steps to reproduce the bug**

First fail a package install
```
❯ tanzu package install cloud-native-runtimes -p cnrs.tanzu.vmware.com -v 1.0.2 -n tap-install -f no-exist.yaml

/ Installing package 'cnrs.tanzu.vmware.com'
| Getting namespace 'tap-install'
| Getting package metadata for 'cnrs.tanzu.vmware.com'
| Creating service account 'cloud-native-runtimes-tap-install-sa'
| Creating cluster admin role 'cloud-native-runtimes-tap-install-cluster-role'
| Creating cluster role binding 'cloud-native-runtimes-tap-install-cluster-rolebinding'
| Creating secret 'cloud-native-runtimes-tap-install-values'

Please consider using 'tanzu package installed delete' to delete the already created associated resources


Error: failed to read from data values file 'no-exist.yaml': open no-exist.yaml: no such file or directory
```

Then use the recommended remediation from the error message of deleting the package.
```
❯ tanzu package installed delete cloud-native-runtimes -n tap-install

Deleting installed package 'cloud-native-runtimes' in namespace 'tap-install'. Are you sure? [y/N]: y

/ Getting package install for 'cloud-native-runtimes'

package 'cloud-native-runtimes' is not installed in namespace 'tap-install'. Deleted previously installed resources
```

Note the message `package 'cloud-native-runtimes' is not installed `

**Version** (include the SHA if the version is not obvious)

```
❯ tanzu version
version: v0.4.0
buildDate: 2021-09-23
sha: 85c7f0fe

~/workspace/tanzu-beta-install ·················································································································· 03:50:18 PM
❯ tanzu package version
v0.4.0
```

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by blc1996** [comment] 2021-10-11 20:50
As far as I'm concerned, this is not a bug. The message already indicated that the previously installed resources were deleted.

However, we can definitely improve the message.

cc @maralavi

**Comment by maralavi** [comment] 2021-10-13 19:06
> Some users have also reported that in the above flow when they run the `tanzu package installed delete` command, it does NOT delete all the resources and they were required to delete each resource one by one. I was not able to reproduce it but still wanted to point it out in case if someone is able to reproduce it when picking up this issue.

Hi @vibhas We couldn't observe such behaviour in our tests. If you know of any existence case, please kindly file the bug so we can fix asap.

**Comment by vijaykatam** [comment] 2021-10-18 18:29
> An alternative is to clean up created resources as part of a failed package install in the package install logic

I am okay with this as a separate feature that a user needs to opt in with something like `--atomic`.  I think this functionality would be lower priority than idempotency of install command.

**Comment by shivaani0505** [comment] 2021-10-20 18:45
The output message from delete "package 'cloud-native-runtimes' is not installed in namespace 'tap-install'. Deleted previously installed resources" is meaningful and describes the exact situation.
Closing this issue as it cannot be reproduced.

**Closed by shivaani0505** 2021-10-20 18:45 UTC
Labels: priority/important-soon, area/addons, kind/bug

**Comment by ssh30** [comment] 2022-09-27 18:43
just to mention that there must be a way of remove all those "API Error: Failed to get package: NotFound (resource not found)" and  the endless "Reconciling" from tmc tab

**Comment by maralavi** [comment] 2022-09-27 18:45
cc: @shyaamsn
