### ISSUE TITLE
CLI output on windows shows ANSI markup

### ISSUE THREAD

**Issue by danfein** [vmware-tanzu/tanzu-framework#3167] opened 2022-08-19 17:45 UTC
**Bug description**

When using the Tanzu CLI with Windows powershell or command prompt any styled text (color, bolding, etc) shows the markup instead of rendering the styling. 

Note: also tested with cygwin, the terminal in vscode, and gitbash (mingw), and all display text styled as expected. After talking with @randomvariable it sounds like the problem is rooted in conhost.exe, which backs the command prompt and powershell.

A similar issue was filed with TCE (currently in icebox) - https://github.com/vmware-tanzu/community-edition/issues/1490

**Affected product area (please put an X in all that apply)**

- ( ) APIs
- ( ) Addons
- (x) CLI
- ( ) Docs
- ( ) IAM
- ( ) Installation
- ( ) Plugin
- ( ) Security
- ( ) Test and Release
- (x) User Experience
- ( ) Developer Experience

**Expected behavior**

Styled text should use a markup that windows conhost.exe supports, or disable styling when conhost.exe is detected to prevent the markup characters from displaying. 

**Steps to reproduce the bug**

Install tanzu CLI on windows machine

From the command prompt, or powershell run as admin

* run 'tanzu -h' or 'tanzu apps workload list'

The bolding on the subheads, and colorization of status in the workload list will display the markup characters. 

**Version** (include the SHA if the version is not obvious)

```
version: v0.25.0
buildDate: 2022-07-28
sha: 8db7108d-dirty
```

**Environment where the bug was observed (cloud, OS, etc)**

* Tanzu CLI version v0.25.0 (1.2.2-build.2 from tanzunet)
* Windows 10, 21H2 
* TAP running on a GCP environment (TAP 1.2.1)

**Relevant Debug Output (Logs, manifests, etc)**

```
←[1mTanzu CLI←[0m

←[1mUsage:←[0m
  tanzu [command]

←[1mAvailable command groups:←[0m

  ←[1mRun←[0m
    cluster                 Kubernetes cluster operations
    kubernetes-release      Kubernetes release operations
    management-cluster      Kubernetes management cluster operations
    package                 Tanzu package management
    standalone-cluster      Create clusters without a dedicated management cluster

  ←[1mSystem←[0m
    completion              Output shell completion code
    config                  Configuration for the CLI
    init                    Initialize the CLI
    login                   Login to the platform
    plugin                  Manage CLI plugins
    update                  Update the CLI
    version                 Version information


←[1mFlags:←[0m
  -h, --help   help for tanzu

Use "tanzu [command] --help" for more information about a command.

Not logged in
```

```
C:\Users\test-user>tanzu apps workload list
NAME        APP       READY                   AGE
pet-img-2   ←[2m<empty>←[0m   ←[31;1mSupplyChainNotFound←[0m     20d
pet-img-5   ←[2m<empty>←[0m   ←[31;1mWorkloadLabelsMissing←[0m   29d
pet-img-6   ←[2m<empty>←[0m   ←[31;1mSupplyChainNotFound←[0m     29d

C:\Users\test-user>
```

**Comment by marckhouzam** [comment] 2022-09-09 01:10
This looks like a duplicate of #352

**Comment by vuil** [comment] 2022-09-12 21:34
marked as duplicated

**Closed by vuil** 2022-09-12 21:34 UTC
Labels: kind/bug, area/ux, area/core-cli
