### ISSUE TITLE
tanzu-cli doesn't work on Windows machines.

### ISSUE THREAD

**Issue by saimanoj01** [vmware-tanzu/tanzu-framework#2282] opened 2022-05-03 00:42 UTC
**Bug description**
```
PS C:\Users\req73903> tanzu version
version: v0.11.2
buildDate: 2022-03-17
sha: 9f16f375


PS C:\Users\req73903> tanzu plugin list
unable to list plugin from discovery 'default': error while processing package: failed to get resource files from discovery: Checking if image is bundle: Fetching image: Get "https://projects.registry.vmware.com/v2/": x509: certificate signed by unknown authority
```

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**

**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by vuil** [comment] 2022-05-03 16:34
Dupe of https://github.com/vmware-tanzu/tanzu-framework/issues/1710?

**Closed** 2022-05-03 16:55 UTC
Labels: area/cli, kind/bug, severity-1
