### ISSUE TITLE
Unable to set up management cluster as cli is unable to install kapp-controller to bootstrap cluster

### ISSUE THREAD

**Issue by shivaani0505** [vmware-tanzu/tanzu-framework#2759] opened 2022-06-25 01:51 UTC
**Bug description**
Unable to set up management cluster as cli is unable to install kapp-controller to bootstrap cluster

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] IAM
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Expected behavior**
MC should be created

**Steps to reproduce the bug**
Create a mc with latest tanzu cli
It will error out at:
```
Bootstrapper created. Kubeconfig: /Users/gshivaani/.kube-tkg/tmp/config_EMC19qsr
User ConfigValues File: /var/folders/nd/q7bzmcrj5g70mdg92q3c7pb00000gp/T/1765616673.yaml
Kapp-controller values-file: /var/folders/nd/q7bzmcrj5g70mdg92q3c7pb00000gp/T/3226015211.yaml
Deleting kind cluster: tkg-kind-car66ri87d5pn4qv0j1g
Error: unable to set up management cluster: unable to install kapp-controller to bootstrap cluster: error while running ytt: 
- struct has no .nodeSelector field or method
    in kapp_controller_values
      kapp-controller.yaml:13 | nodeSelector: #@ data.values.nodeSelector
    in <toplevel>
      kapp-controller.yaml:23 | --- #@ template.replace(kapp_controller_lib.with_data_values(kapp_controller_values()).eval())
Error: exit status 1
```

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by shyaamsn** [comment] 2022-06-25 01:52
Duplicate of https://github.com/vmware-tanzu/tanzu-framework/issues/2758

**Closed by shyaamsn** 2022-06-25 01:52 UTC
Labels: area/addons, kind/bug, needs-triage
