### ISSUE TITLE
Setting Tanzu Bash completion causes error : storage: object doesn't exist

### ISSUE THREAD

**Issue by RussellHamker** [vmware-tanzu/tanzu-framework#1936] opened 2022-03-28 18:40 UTC
## Bug Report

I run the below commands during building a Ubuntu 20.04 OVA to allow for bash auto-completion. Validating the command gives me an error. 

OVA is built using packer. I am using sudo during the packer build process. to allow for this to attempt this. I have no issues running a similar command for kubectl.

Tanzu Cli install process: 
Downloading Tanzu gz file and exploding it via sudo
Install NOT using sudo using the ./install.sh script.

Command:
tanzu completion bash | sudo tee /etc/bash_completion.d/tanzu > /dev/null
or
/usr/local/bin/tanzu completion bash | sudo tee /etc/bash_completion.d/tanzu > /dev/null

## Expected Behavior

There should be no error and bash completion should not have an issue.

If I run this command after deploying the OVA, I do not get this error and bash completion works correctly.

## Steps to Reproduce the Bug

When you cat /etc/bash_completion.d/tanzu, you get the below:

administrator@tanzu:~$ cat /etc/bash_completion.d/tanzu
| initializing
✖  could not read artifact "artifacts/pinniped-auth/v0.11.2/tanzu-pinniped-auth-linux_amd64": storage: object doesn't exist

## Screenshots or additional information and context

vi /etc/bash_completion.d/tanzu provides this:
![image](https://user-images.githubusercontent.com/102260516/160464376-9f692568-6134-4546-adb4-6de8f2137cbf.png)

When you reboot/ssh into the OVA, you receive:
![image](https://user-images.githubusercontent.com/102260516/160464744-fd6368b6-6b06-4974-83a4-de860e87341a.png)

## Environment Details

* Build version (`tanzu version`): v0.10.1
* Deployment (Managed/Unmanaged cluster): Any cluster, this is a CLI issue.
* Infrastructure Provider (Docker/AWS/Azure/vSphere): Docker/Ubuntu 20.04 LTS
* Operating System (client): Ubuntu 20.04 LTS

**Comment by RussellHamker** [comment] 2022-03-28 22:06
I have found a bad workaround. I have configured this on a system successfully post OVA deployment. I have exported the /etc/bash_completion.d/tanzu script and copied it to my packer instance and have added this file as part of the packer OVA build process.

I believe this issue is caused from the complexity of how you must install tanzu cli without sudo privileges. The ultimate fix will be when Tanzu TCE is installed as a package instead of by a ./install.sh script.

**Comment by marckhouzam** [comment] 2022-08-09 16:19
Hi @RussellHamker.  I've checked-out version `v0.10.1` and notice that this old version of the tanzu cli would automatically try to initialize even when generating the bash completion script.  And then I get the same type of error you do, probably because my installation is not valid. 
```
$ ./tanzu completion bash
\ initializing
✖  could not read artifact "artifacts/pinniped-auth/v0.25.0/tanzu-pinniped-auth-darwin_arm64": storage: object doesn't exist
```
The latest version of the CLI does not behave this way anymore.
Would you be able to try a more recent version?  I expect the problem will no longer be present.

**Comment by marckhouzam** [comment] 2022-08-17 14:21
I'll close this as I believe newer versions of the CLI don't have this problem.
Please re-open if the problem is still present with a recent version.

**Closed by marckhouzam** 2022-08-17 14:21 UTC
Labels: area/cli, area/plugin, kind/bug, area/ux, area/core-cli
